---
title: "Environments"
teaching: 
exercises: 
---

:::::::::::::::::::::::::::::::::::::: questions

- What is a project environment and why does it matter?
- How can we create project environment?

::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::: objectives

- Explain the purpose of an project environment.
- Create a project environment using `renv`.
- Add packages to the `renv` environment directly and from a `DESCRIPTION` file.
- Use use `renv::snapshot()` to take implicit and explicit snapshots of the environment.
- Restore an environment on a different machine using `renv::restore()` which recreates the environment on another machine.

::::::::::::::::::::::::::::::::::::::::::::::::

## Inheriting an R script

A colleague hands you an R script called `sleep_analysis.R` and asks you to reproduce their results while their away.

## Create an R project

Before working with the script, create an R project in RStudio:
- Go to File > New Project > New Directory > New Project
- Name the directory `rworkshop`
- Create as a subdirectory of your home directory (for example: `C:/Users/username/`)
- Click "Create Project"
 
If you want to come back to your work later, open the R Project file you created (`rworkshop.Rproj`). Double‑clicking this file launches RStudio, sets the working directory, and restores your project as you left it.

## Save the script

Create a new R script called `sleep_analysis.R` inside the `rworkshop` folder and save the file after pasting in the following code:

``` R
library(obscurepackage)
library(ggplot2)

data <- sleep
none_transformed_data <- none_transform(data$extra)

p <- ggplot(data, aes(x = group, y = none_transformed_data)) +
  geom_boxplot() +
  labs(
    title = "Extra Sleep by Drug Group",
    x = "Drug Group",
    y = "Extra sleep (hours)"
  )

print(p)
```

## Run the script

You will probably hit an error when you try to run `sleep_analysis.R`.

The script tries to load:
``` R
library(obscurepackage)
```
But on your machine, that package is not installed, resulting in an error message that looks like the one below.

``` R
Error in library(obscurepackage) : 
  there is no package called ‘obscurepackage’
```

## Missing package

On your machine, R looks for packages in your global environment. You might already have `ggplot2` installed, but you probably don not have `obscurepackage` installed, so the script fails.

::::::::::::::::::::::::::::::::::::: challenge
## Try to make the script run

- Install the missing package(s) so the script can run
- Re-run the script and reproduce the boxplot figure

You may already have `ggplot2` installed, but if not, you can install it with:

```r
install.packages("ggplot2")
```

The `obscurepackage` is not on CRAN. You need to install it from GitHub:
``` R
remotes::install_github("stellaprins/obscurepackage")
```

Now that you have installed the required packages, are you able to reproduce the plot? Why?

[sleep analysis plot](episodes\fig\sleep_analysis_plot.png)

:::::::::::::::::::::::: solution
## version matters 

The newest version of `obscurepackage` contains a bug that causes `none_transform()` to always return `NA`, so the boxplot cannot be reproduced unless you install the earlier version.

[sleep analysis NA plot](episodes\fig\sleep_analysis_NA_plot.png)

:::::::::::::::::::::::::::::::::::::

## version mismatch

A version mismatch happens when your script loads a package whose functions have changed between releases, causing the same code to produce different results on different machines.

## project environments

Installing inside a project environment ensures:
- the project environment keeps a record of which packages are used
- the exact versions of those packages are recorded
- the environment can be recreated on different machines or at a later timepoint

::::::::::::::::::::::::::::::::::::: callout
## Two different meanings of environment in R

**1) project environments**  
These are external, project‑specific libraries created by the `renv` package. 
They store **packages and their versions**, making your project reproducible on any machine.

**2) R environments**  
These store variables and track where functions were created, and control how R finds values.  
They enable features like **lexical scoping** and **namespaces**.
::::::::::::::::::::::::::::::::::::::::::::::::

# `renv`

In this workshop, we are going to use an R package called `renv` to manage our project environment.

To install `renv`
``` R 
install.packages("renv")
```

::::::::::::::::::::::::::::::::::::: challenge
## Find out more about `renv`

Use the R console to learn more about `renv`.
``` R
help(renv)
```

Explore the help page and useful links.

Summarise what `renv` is and and how it helps with project handovers.

:::::::::::::::::::::::: solution
## Initialise renv

`renv` is an R package that helps create reproducible environments.

One of the reasons to use `renv` is to make it easier to share your code in such a way that everyone gets exactly the same package versions as you. 

:::::::::::::::::::::::::::::::::::::

Initialise `renv`:

``` R
renv::init()
```

This will:
- Set up project infrastructure inside your working directory that ensures `renv` will be used in future sessions
- Discover the packages that are currently installed, and install them into the project library folder where renv puts the packages that this project uses
- Create a file named `renv.locks` that records the state of the project library so it can be restored by others
- Restart R.

## Install packages are in the renv environment

Any package you install into your `renv` will be kept isolated from whatever is installed globally on your machine.

### Install ggplot2 from CRAN

Use `renv::install()` to install ggplot2 directly into the renv environment:
``` r
renv::install("ggplot2")
```

::::::::::::::::::::::::::::::::::::: challenge
## Install a GitHub package using `renv`

Use the help page for `renv::install` to learn how to install packages inside the `renv` environment.
``` R
?renv::install
```

- Use the help page to find out how to install a package from GitHub using `renv::install()`
- Use what you learned to install `v0.1.0` of the GitHub repository `stellaprins/obscurepackage`.

:::::::::::::::::::::::: solution
## 
From the help page, GitHub packages can be installed by using the `username/repository` string, and specific versions can be installed by supplying a commit SHA.

The commit SHA for `v0.1.0` of `stellaprins/obscurepackage` is `9e7cfcba9bfbfd1cbea4dbc1600f8d5283c71831`.


```R
renv::install("stellaprins/obscurepackage@9e7cfcba9bfbfd1cbea4dbc1600f8d5283c71831")
```

:::::::::::::::::::::::::::::::::::::

### Install obscurepackage from GitHub

To install a specific version of a GitHub package inside an renv project, use `the username/repo@version` format:

```R
renv::install("stellaprins/obscurepackage@v0.1.0")
```

Restart RStudio and rerun the `sleep_analysis.R` script.

You should be able to replicate the results of your colleague!

## Checking the environment with `renv::status()`

To check whether your project environment is consistent with your lockfile, use:
``` r
renv::status()
```

`renv::status()` compares three things:
- `renv` project library
- the `renv.lock` file
- What your project actually uses

If these differ, `renv::status()` will report inconsistencies such as:
- packages installed but not recorded
- packages recorded but not installed
- packages where the installed version ≠ recorded version
- a different R version than the one used to generate the lockfile

::::::::::::::::::::::::::::::::::::: challenge
## Fix `renv` status inconsistencies
Run:

``` r
renv::status()
```

Look at the output.

Now take a "snapshot using `renv::snapshot()`":
```r 
renv::snapshot()
```

Then, run `renv::status` again :

``` r
renv::status()
```

Compare the `renv::status` outputs before and after taking a snapshot:
- Which inconsistencies disappeared?
- Which (if any) remain?
- Why did snapshotting fix these issues?

:::::::::::::::::::::::: solution

After running `renv::snapshot()` the second time, you will (hopefully!) see something like
``` r 
No issues found -- the project is in a consistent state.
```

All of the inconsistencies should have disappeared because `renv::snapshot()` rewrites the lockfile to reflect the current state of your project library and R version.
:::::::::::::::::::::::::::::::::::::

## 

Use `renv::snapshot()` to update a lockfile with the current state of dependencies in the project library. 

``` R
renv::snapshot()
```

Later, you or a collaborator can use it to recreate the same environment with:

``` R
renv::restore()

```

Use `renv::restore()` when:
- you open a project on a new computer
- you clone someone else's project from GitHub
- you want to return to a known working state


## `DESCRIPTION`

Your colleague emails you  — apparently the earlier file (`sleep_analysis.R`) was the wrong one.

This time, they’ve sent two files:
    `sleep_analysis.R`
    `DESCRIPTION`

Place the files in your `rworkshop` folder.

:::::::::::::::::::::::: challenge
## Learn more about `DESCRIPTION` files

Open the `DESCRIPTION` file in RStudio. What information does the file contain?

:::::::::::::::::::::::: solution

This particular `DESCRIPTION` contains one field, `Imports`, which lists the project’s dependencies and the minimum required version for each package.

``` R
Imports:
    dplyr (>= 1.1.0),
    tidyr (>= 1.3.0),
    ggplot2 (>= 3.4.0)

```
:::::::::::::::::::::::::::::::::::::


:::::::::::::::::::::::: challenge
## `renv::dependencies()`
Run `renv::dependencies()`:

``` R
renv::dependencies()
```
What packages does `renv` detect, and where does it say they come from?

:::::::::::::::::::::::: solution

renv detects packages listed in the `DESCRIPTION` file and imported in the R scripts.

`renv` shows the source of each dependency:
- Packages listed in `DESCRIPTION` appear under `Type = Imports`
- Packages found only in scripts appear with `Type = <NA>`

:::::::::::::::::::::::::::::::::::::

### Reset the environment

First make sure `ggplot2` and `obscurepackage` are removed from the global R library.
``` R
remove.packages("ggplot2")
remove.packages("obscurepackage")
```

Then remove the `renv` project library and lockfile, and restart R.
``` R
unlink("renv/library", recursive = TRUE)   
unlink("renv.lock")                        
.rs.restartR()                             
```

Now you are back in the same situation as before setting up the environment.

Because `ggplot2` is definitely removed from the global library, you can test whether renv correctly installs everything based on the `DESCRIPTION` file.

Try running `sleep_analysis_final.R`. It should fail with an error. The script cannot run until renv installs the required packages.

Use `renv::install()` to install all packages in the`Imports` field.
``` R
renv::install()
```

:::::::::::::::::::::::::::::::::::::::: solution

::::::::::::::::::::::::::::::::::::: keypoints
- An **R environment** defines the exact versions of R and packages used in a project.
- `renv` creates isolated, project‑specific libraries for reproducible workflows.
- Reproducibility depends on stable, well‑defined environments.

::::::::::::::::::::::::::::::::::::::::::::::::
